# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_doctor_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='rating.University'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='logo',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(upload_to='img'),
        ),
    ]
