# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20180208_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='rating.University'),
        ),
    ]
